### PR TITLE
Release workflow with cross-compilation build

### PR DESCRIPTION
**Pull request by marcauberer**
- Add release workflow with compiler binary cross-compilation for following targets:
   - `linux-arm64`
   - `linux-armv5`
   - `linux-armv6` (currently uncommented. Waiting for a third party fix here)
   - `linux-armv7`
   - `linux-x86`
   - `linux-x64`
   - `windows-x86`
   - `windows-x64`
- Add workflow steps for building compiler cli binaries with Goreleaser
- Re-create Go module
- Refactoring

### CODE REVIEW

**Review by Splines — COMMENTED** [review]
Sorry, the `.goreleaser.yml` is over my head right now with all those arguments ;) Can't really help here...

**Comment by marcauberer** [comment]
> Sorry, the `.goreleaser.yml` is over my head right now with all those arguments ;) Can't really help here...

@Splines No problem. If you are interested in Go release pipelines, you can visit Goreleaser's docs [here](https://goreleaser.com). There you can find all the attributes.
You don't have to review this pr. It contains a lot low-level packaging stuff. (And it is not quite finished yet)

**Comment by marcauberer** [comment]
Have to wait with this pr until the next release of Gorelease itself to contain my contribution, which was merged in the meantime ...

**Comment by marcauberer** [comment]
@Splines do you want to review this pr once again or should I merge it?

**Pull request merged**
